In [13]:
import cv2

image = cv2.imread("../../data/test_images/word_images/test2.png")

# กำหนดขอบเขตการ Crop
start_row, end_row = 0, 115  # กำหนดช่วงแถว
start_col, end_col = 0, 311  # กำหนดช่วงคอลัมน์

cropped_image = image[start_row:end_row, start_col:end_col]

#cv2.imshow("crop 1", image)
cv2.imshow("crop 2", cropped_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Crop หลายส่วนในภาพ

In [6]:
import cv2

image = cv2.imread("../../data/test_images/word_images/test2.png")
crop_regions = [(100, 300, 50, 200), (100, 200, 300, 400)]  # (start_row, end_row, start_col, end_col)

for idx, (start_row, end_row, start_col, end_col) in enumerate(crop_regions):
    cropped_image = image[start_row:end_row, start_col:end_col]
    cv2.imshow(f"Cropped Image {idx + 1}", cropped_image)

cv2.waitKey(0)
cv2.destroyAllWindows()

## Crop ภาพแบบอัตโนมัติตาม Contours

In [9]:
import cv2

# โหลดภาพและแปลงเป็น Grayscale
image = cv2.imread("../../data/test_images/word_images/word_1.jpg")
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# หาขอบเขต (Contours)
_, binary = cv2.threshold(gray, 128, 255, cv2.THRESH_BINARY)
contours, _ = cv2.findContours(binary, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

# Crop เฉพาะส่วนที่เจอ Contours
for idx, contour in enumerate(contours):
    x, y, w, h = cv2.boundingRect(contour)  # กรอบสี่เหลี่ยมรอบ Contour
    cropped_image = image[y:y+h, x:x+w]  # Crop โดยใช้ค่าจาก boundingRect
    cv2.imshow(f"Cropped Object {idx + 1}", cropped_image)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [21]:
import numpy as np
image = [[[1],[2],[3]], [[4],[5],[6]]]
image_array = np.array(image)
print(image_array.shape)

(2, 3, 1)


## ใช้ Mask

In [12]:
import cv2
import numpy as np

# โหลดรูปภาพ
image = cv2.imread('../../data/test_images/cat.png')

# สร้าง mask ว่าง
mask = np.zeros(image.shape[:2], dtype=np.uint8)

# กำหนดจุดสำหรับ polygon ที่ต้องการ crop
polygon = np.array([[50, 50], [200, 50], [200, 200], [50, 200]], dtype=np.int32)

# วาด polygon ลงบน mask
cv2.fillPoly(mask, [polygon], 255)

# ใช้ mask กับรูปภาพ
result = cv2.bitwise_and(image, image, mask=mask)

In [13]:
cv2.imshow('Original', image)
cv2.imshow('Mask', mask)
cv2.imshow('Cropped', result)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [40]:
import cv2
import numpy as np

# โหลดรูปภาพ
image = cv2.imread('../../data/test_images/word_images/word_35.jpg')

# แปลงภาพเป็นขาวดำ (Grayscale)
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# ใช้ Threshold เพื่อแยกตัวอักษร
_, binary = cv2.threshold(gray, 200, 255, cv2.THRESH_BINARY_INV)

kernel = np.ones((5, 1), np.uint8)
dummy_image = cv2.dilate(binary, kernel, iterations=1)

# หาขอบเขตของตัวอักษร (Bounding Boxes)
contours, _ = cv2.findContours(dummy_image, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

# วาดกรอบรอบตัวอักษรและแยกแต่ละตัวออก
print(contour[0][0])
for i, contour in enumerate(contours):
    print(i)
    print(contour)
    #x, y, w, h = cv2.boundingRect(contour)

    
    #cropped_char = binary[y:y+h, x:x+w]  # ตัดตัวอักษรแต่ละตัว
    #cv2.imshow(f'Character {i}', cropped_char)  # แสดงแต่ละตัวอักษร

#cv2.imshow('Original', image)
#cv2.imshow('binary', binary)
#cv2.imshow('dummy_image', dummy_image)
#cv2.waitKey(0)
#cv2.destroyAllWindows()

[154  32]
0
[[[205  49]]

 [[203  51]]

 [[203  52]]

 [[202  53]]

 [[202  66]]

 [[204  66]]

 [[204  65]]

 [[207  62]]

 [[207  61]]

 [[209  59]]

 [[209  55]]

 [[210  54]]

 [[211  55]]

 [[211  66]]

 [[212  66]]

 [[212  51]]

 [[210  49]]]
1
[[[188  49]]

 [[187  50]]

 [[187  55]]

 [[188  56]]

 [[189  56]]

 [[190  57]]

 [[189  58]]

 [[188  58]]

 [[187  59]]

 [[187  65]]

 [[188  66]]

 [[191  66]]

 [[191  64]]

 [[192  63]]

 [[193  63]]

 [[194  64]]

 [[195  64]]

 [[197  66]]

 [[198  66]]

 [[198  49]]

 [[197  49]]

 [[197  60]]

 [[196  61]]

 [[193  58]]

 [[192  58]]

 [[191  57]]

 [[191  50]]

 [[190  49]]]
2
[[[173  49]]

 [[172  50]]

 [[172  55]]

 [[173  56]]

 [[174  56]]

 [[175  57]]

 [[175  66]]

 [[176  66]]

 [[179  63]]

 [[179  62]]

 [[181  60]]

 [[181  59]]

 [[182  58]]

 [[183  59]]

 [[183  66]]

 [[184  66]]

 [[184  50]]

 [[183  49]]

 [[181  49]]

 [[180  50]]

 [[180  56]]

 [[178  58]]

 [[178  59]]

 [[177  60]]

 [[176  59]]

 [[1